# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Softin.co'
tagline:             'A Tiny Software Company'
description:         ''
url:                 http://softin.co

baseurl:             /
paginate:            5
excerpt_separator:   ''

# About/contact
author:
  name:              'Softin.co Team'
  url:               https://twitter.com/softinco
  email:             darkdeny@gmail.com

# Custom vars
version:             1.0.0
